backend:
  name: github
  repo: dalemorgan04/Gridsome-OSB

media_folder: "src/assets/uploads"
public_folder: ""

collections:
  - label: "Pages"
    name: "pages"
    description: "Content and settings for individual pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/pages/home.yml"
        fields:
          - label: "Landing Section"
            name: "landingSection"
            widget: "object"
            fields:            
              - {label: "Title", name: "landingTitle", widget: "string"}
              - {label: "Subtext", name: "landingSubtext", widget: "string"}
              - label: "Carousel Images"
                name: "landingImages"
                widget: "list"
                fields:
                  - {label: "Landing Image", name: "landingImage", widget: "image"}
          - label: "Summary Section"
            name: "summarySection"
            widget: "object"
            fields:
              - {label: "Title", name: "summaryTitle", widget: "string"}
              - {label: "Text", name: "summaryText", widget: "string"}
              - {label: "Static Image", name: "summaryImage", widget: "image"}
          - label: "Feature Projects"
            name: "featureProjects"
            widget: "object"
            fields:
              - label: "Image 1"
                name: "featureImage1"
                widget: "object"
                fields:
                  - {label: "Image 1", name: "featureImage1", widget: "image"}              
                  - {label: "Image 1 Title", name: "featureTitle1", widget: "string"}
                  - {label: "Image 1 Description", name: "featureText1", widget: "string"}
              - label: "Image 2"
                name: "featureImage2"
                widget: "object"
                fields:
                  - {label: "Image 2", name: "featureImage2", widget: "image"}              
                  - {label: "Image 2 Title", name: "featureTitle2", widget: "string"}
                  - {label: "Image 2 Description", name: "featureText2", widget: "string"}
              - label: "Image 3"
                name: "featureImage3"
                widget: "object"
                fields:
                  - {label: "Image 3", name: "featureImage3", widget: "image"}
                  - {label: "Image 3 Title", name: "featureTitle3", widget: "string"}
                  - {label: "Image 3 Description", name: "featureText3", widget: "string"}
              - label: "Image 4"
                name: "featureImage4"
                widget: "object"
                fields:
                  - {label: "Image 4", name: "featureImage4", widget: "image"}
                  - {label: "Image 4 Title", name: "featureTitle4", widget: "string"}
                  - {label: "Image 4 Description", name: "featureText4", widget: "string"}
      - label: "About Page"
        name: "about"
        file: "content/pages/about.yml"
        fields:
          - {label: "Content", name: "body", widget: "markdown"}
  - label: "Settings"
    name: "settings"
    description: "General site information and settings"
    files:
      - label: "Site Settings"
        name: "siteSettings"
        file: "content/settings/site-settings.yml"
        fields:
          - {label: "Site Name", name: "siteName" , widget: "string" }