backend:
  name: github
  repo: dalemorgan04/Gridsome-OSB

media_folder: "static/uploads"
public_folder: "/uploads"
site_url: "https://osbarchitects.netlify.app"

collections:
  - label: "Pages"
    name: "pages"
    description: "Content and settings for individual pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/pages/home.yml"
        fields:
          - label: "Landing Section"
            name: "landing"
            widget: "object"
            fields:            
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtext", name: "text", widget: "string"}
              - label: "Carousel Images"
                name: "carousel"
                widget: "list"
                fields:
                  - {label: "Landing Image", name: "image", widget: "image"}
          - label: "Summary Section"
            name: "summary"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Static Image", name: "image", widget: "image"}
          - label: "Feature Projects"
            name: "projects"
            widget: "object"
            fields:
              - label: "Project 1"
                name: "project1"
                widget: "object"
                fields:
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "text", widget: "string"}
              - label: "Project 2"
                name: "project2"
                widget: "object"
                fields:
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "text", widget: "string"}
              - label: "Project 3"
                name: "project3"
                widget: "object"
                fields:
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "text", widget: "string"}
              - label: "Project 4"
                name: "featureProject4"
                widget: "object"
                fields:
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "text", widget: "string"}
      - label: "About Page"
        name: "about"
        file: "content/pages/about.yml"
        fields:
          - {label: "Content", name: "body", widget: "markdown"}
  - label: "Settings"
    name: "settings"
    description: "General site information and settings"
    files:
      - label: "Site Settings"
        name: "siteSettings"
        file: "content/settings/site-settings.yml"
        fields:
          - {label: "Site Name", name: "siteName" , widget: "string" }